# Generated by Django 6.0.5 on 2026-06-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0003_alter_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
