# Generated by Django 6.0.5 on 2026-06-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0004_remove_account_user_remove_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='monthly_income_before_taxes',
            new_name='monthly_net_income',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
