# Generated by Django 6.0.5 on 2026-06-12 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0012_incomecustomization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCustomizationWithCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='in', max_length=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FinanceAdminApp.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FinanceAdminApp.category')),
                ('credit_card_transaction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='FinanceAdminApp.creditcardtransaction')),
                ('income_customization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FinanceAdminApp.incomecustomizationwithcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
