# Generated by Django 6.0.5 on 2026-06-12 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0013_creditcardtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecustomizationwithcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='FinanceAdminApp.category'),
        ),
        migrations.AddField(
            model_name='incomecustomizationwithcategory',
            name='income_customization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='FinanceAdminApp.incomecustomization'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='incomecustomizationwithcategory',
            name='percentage',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
