# Generated by Django 6.0.5 on 2026-06-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0014_incomecustomizationwithcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecustomizationwithcategory',
            name='income_customization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FinanceAdminApp.incomecustomization'),
        ),
    ]
