# Generated by Django 6.0.5 on 2026-06-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0015_alter_incomecustomizationwithcategory_income_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecustomizationwithcategory',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
