# Generated by Django 6.0.5 on 2026-06-13 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0016_alter_incomecustomizationwithcategory_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecustomizationwithcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceAdminApp.category'),
        ),
        migrations.AlterField(
            model_name='incomecustomizationwithcategory',
            name='income_customization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceAdminApp.incomecustomization'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit_card_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceAdminApp.creditcardtransaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='income_customization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceAdminApp.incomecustomizationwithcategory'),
        ),
    ]
