# Generated by Django 6.0.5 on 2026-06-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0016_alter_incomecustomizationwithcategory_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
