# Generated by Django 6.0.5 on 2026-06-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0017_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='income_customization',
        ),
    ]
