# Generated by Django 6.0.5 on 2026-06-13 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0018_remove_transaction_income_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='credit_card_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='FinanceAdminApp.creditcardtransaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=5),
        ),
    ]
