# Generated by Django 6.0.5 on 2026-06-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0017_alter_incomecustomizationwithcategory_category_and_more'),
        ('FinanceAdminApp', '0019_alter_transaction_credit_card_transaction_and_more'),
    ]

    operations = [
    ]
