# Generated by Django 6.0.5 on 2026-06-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0022_alter_periodictransaction_periodic_type_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictransaction',
            name='periodic_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('every15days', 'Every 15 days'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
