# Generated by Django 6.0.5 on 2026-06-17 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0025_income_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='periodic_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceAdminApp.periodictransaction'),
        ),
    ]
