# Generated by Django 6.0.5 on 2026-09-20 02:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceAdminApp', '0026_transaction_periodic_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceAdminApp.account'),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceAdminApp.category'),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='periodic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditcardtransaction',
            name='periodic_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FinanceAdminApp.periodictransaction'),
        ),
        migrations.AlterField(
            model_name='creditcardtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
